### PR TITLE
edit README file, add instructions for developers to add .env files

### PR DESCRIPTION
**Pull request by KateChern**
Update README, add instructions explaining that developers must add .env.test and .env.development files to successfully connect to the two databases locally

### CODE REVIEW

**Review by antariess — COMMENTED** [review]
please add what the user needs to include in those two files.

**Comment by KateChern** [comment]
add .env.test and .env.development files and into each, add PGDATABASE=nc_news_test, and PGDATABASE=nc_news respectively.

**Review by popatre — CHANGES_REQUESTED** [review]
Just needs a bit more instructions. 
What are they adding inside the .env.test and .env.development files?

**Comment by KateChern** [comment]
You will need to create two .env files for your project: .env.test and .env.development. Into each, add PGDATABASE=<database_name_here>, with the correct database name for that environment (see /db/setup.sql for the database names). Double check that these .env files are .gitignored.

**Pull request closed without merging**
